### ISSUE TITLE
BioConductor submission

### ISSUE THREAD

**Issue by sthawinke** [CenterForStatistics-UGent/reconsi#1]
@JoFAM We are planning to submit this to BioConductor and set you as maintainer, once we received reviewers' comments. Any comments/suggestions in the meanwhile?

**Comment by sthawinke** [comment]
@JoFAM  we will not await reviewer comments, and I am planning to submit later this week. Could you please indicate if you have any suggestions? Thanks!

**Comment by JoFAM** [comment]
In de branch Joris_Remarks: 

- Removed the README file using .Rbuildignore from the .tar.gz : commit e0177b0e8ac0d62f65082c9d8694121206623fb6

 - Changed title case (I know, silly thing, but it gets flagged by automatic checks) : commit 180e47667ca04364a6e6746bf38ecf27c2ae19ad

- Corrected typo in error messages `reconsi()` : commit 9c88ea2

There's a note about examples taking more than 5 seconds (up to almost a minut for `reconsi()` and close to half a minute for `testDAA()` ). This will be flagged as well and likely will lead to the question to reduce the computation time of the examples. 

I've seen a few opportunities for improving performance of the code, but that'll take me a bit more time.

**Comment by sthawinke** [comment]
Package accepted, thanks for your help!
